### ISSUE TITLE
Add 7d average to the data table displayed on the website

### ISSUE THREAD

**Issue by bogosj** [rutherford-nj/data-committee.covid-data#10]
Perhaps to the left of the 14d column.

**Comment by grecine** [comment]
we have two versions of that output, a [14d version](https://github.com/rutherford-nj/data-committee.covid-data/blob/main/docs/cases_Rutherford_14d_SMA.html) and a [7d version](https://github.com/rutherford-nj/data-committee.covid-data/blob/main/docs/cases_Rutherford_7d_SMA.html).

I can do two things, one easy and one correct:

- EASY: add a 7d avg to the 14d version
- CORRECT: make a new version (cases_Rutherford_14d_7d_SMA.html) with both

which do you prefer? The easy way has the benefit of you having to do no changes on the web page, but then the filename is a lie ;)

**Comment by grecine** [comment]
and, damnit, I forgot that I wrote this is only one value for the simple moving average. I can still do it, but it'll be a *bit* more work on my part. And really easy to add it to the 14d version now

**Comment by bogosj** [comment]
Just add it to the existing file.

**Comment by grecine** [comment]
![image](https://user-images.githubusercontent.com/2029941/150616343-69731ca0-c009-40d9-940d-93f673d51446.png)

Like that? Right now it's dumping to a new file, but I'll make it overwrite the [14d version](https://github.com/rutherford-nj/data-committee.covid-data/blob/main/docs/cases_Rutherford_14d_SMA.html) and push that change.

I don't like it, but I'll do it.

EDIT: give a thumbs up and thy will be done

**Comment by bogosj** [comment]
Ok fine, keep it in a new file. I'll update the website.

**Comment by grecine** [comment]
closed with commit above.

new file is called: cases_Rutherford_Nd_SMA_and_N/2d_SMA.html

**you want to link to cases_Rutherford_14d_SMA_and_7d_SMA.html**
