### ISSUE TITLE
Stop using COVID Tracking Project

### ISSUE THREAD

**Issue by bogosj** [rutherford-nj/data-committee.covid-data#2]
They [posted today](https://covidtracking.com/analysis-updates/covid-tracking-project-end-march-7) that they will stop updating on March 7th. For now the easiest thing would be to start using the NYTimes data that's already in the repo.

**Comment by bogosj** [comment]
Please assign #3 to me when you've made the change in the charting.

**Comment by grecine** [comment]
Commit b3e5f3c fixes this. Now using NY Times data only. Graphs look the same to the eye, except for the NJ/Bergen Jan 4 change in reporting spike. Now assigning @bogosj to #3
