### ISSUE TITLE
Stop deleting files in the docs directory

### ISSUE THREAD

**Issue by bogosj** [rutherford-nj/data-committee.covid-data#4]
Since we delete all graphs created by the automated process, we should put them in a self-contained directory so we can publish other things manually in the `docs` directory.

@grecine - thoughts on a directory name? `docs/generated`?

**Comment by grecine** [comment]
`docs/published` sounds better. A lot of plots are generated, but only some get published to the web site

**Comment by bogosj** [comment]
We're going to stop deleting things instead.

**Comment by bogosj** [comment]
Done in https://github.com/rutherford-nj/data-committee.covid-data/commit/3f12d77e91782bc7007d9d9180012de499c9f24c
