### ISSUE TITLE
Dump town data to a html "spreadsheet" page

### ISSUE THREAD

**Issue by grecine** [rutherford-nj/data-committee.covid-data#6]
this is to stop the manual editing of a google sheet that is not really used for anything.

@bogosj, once this is done, I'll do a PR for the web site, that cool?

**Comment by bogosj** [comment]
Yes. I'll also have to update the existing published spreadsheet to redirect people who have bookmarked the spreadsheet directly.

**Comment by grecine** [comment]
This fits in with #1 , I can also include the 14d fitted avg and trajectory values on the sheet.

**Comment by grecine** [comment]
fixed in commit 0621645 and b351392 -- file is docs/Rutherford_Cases.html

@bogosj can I close this or do I need to do a PR for the web page on the borough site?

**Comment by bogosj** [comment]
This issue is complete. We should have another to document what our plans are for the borough site.
