### ISSUE TITLE
parameterize demo plot generator for James

### ISSUE THREAD

**Issue by grecine** [rutherford-nj/data-committee.covid-data#9]
happy @bogosj ?

**Comment by bogosj** [comment]
Maybe when it's closed...

**Comment by grecine** [comment]
The important ENVs to set are: YEAR, DEMO_DATA, CASES_FILE

Example: YEAR='2020' CASES_FILE='2020.csv' DEATHS_FILE='2020-deaths.csv' python ./town_demo_plots.py

Env var config input:
    YEAR [str] = calendar year you're running for (used for plot title and quarterly plots)
    PLT_FMT [str] = 'jpg' or 'svg
    DPI [int] = plot dpi
    DEMO_DIR [str] = where your demo data is located
    CASES_FILE [str] = name of the csv file for cases
    DEATHS_FILE [str] = name of the csv file for deaths
    OUT_DIR [str] = output directory
    QUARTERS [bool] = Do plots for quarterly demographics
    PLOT_TO_SCREEN [book] = Show plots on screen as processing
